# Generated by Django 4.2.18 on 2025-01-24 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='commsion',
            new_name='commision',
        ),
    ]
